SET DEFINE OFF
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (1, 1, 1, 'aaa@aaa.com', 68800.0, '카드');
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (2, 2, 1, 'zya@zya.com', 68800.0, '카드');
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (3, 3, 1, 'sjp@sjp.com', 68800.0, '카드');
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (4, 4, 1, 'wsc@wsc.com', 68800.0, '카드');
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (5, 5, 1, 'dmk@dmk.com', 68800.0, '카드');
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (6, 6, 1, 'gek@bbb.com', 68800.0, '카드');
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (7, 7, 1, 'mjk@mjk.com', 68800.0, '카드');
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (8, 8, 1, 'shl@shl.com', 68800.0, '카드');
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (9, 9, 1, 'syl@syl.com', 68800.0, '카드');
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (10, 10, 1, 'tlk@tlk.com', 68800.0, '카드');
INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (11, 11, 1, 'tlk@tlk.com', 65800.0, '카드');

INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (12, 12, 1, 'myp@myp.com', 65800.0, '카드');

INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (13, 13, 1, 'hdn@hdn.com', 65800.0, '카드');

INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (14, 14, 1, 'ejb@ejb.com', 65800.0, '카드');

INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (15, 15, 1, 'yrk@yrk.com', 65800.0, '카드');

INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (16, 16, 1, 'jwm@jwm.com', 65800.0, '카드');

INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (17, 17, 1, 'jks@jks.com', 65800.0, '카드');

INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (18, 18, 1, 'dsn@dsn.com', 65800.0, '카드');

INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (19, 19, 1, 'dms@dms.com', 65800.0, '카드');

INSERT INTO PAY (PAY_NO, ORDER_NO, P_NO, EMAIL, TOTAL_SUM, PAY_METHOD) 
VALUES (20, 20, 1, 'jph@jph.com', 65800.0, '카드');
commit;
